---
abstract: 'Memory mapping made simple and safe.'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  Config: 0
  File::Find: 0
  File::Temp: 0
  IO::Handle: 0
  IO::Socket::INET: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
  Time::HiRes: 0
  if: 0
  open: 0
  utf8: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
keywords:
  - mmap
  - memory
  - mapping
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Map
requires:
  Carp: 0
  Const::Fast: 0
  PerlIO::Layers: 0
  Sub::Exporter::Progressive: 0
  XSLoader: 0
  perl: 5.008
  strict: 0
  subs: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=File-Map
  repository: git://github.com/Leont/file-map.git
version: 0.53
